# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  name: WindowVm

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21.0.2'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: PowerShell@2
    displayName: 'List Contents of Staging Directory'
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Recurse

  - task: CopyFiles@2
    inputs:
      Contents: '**/*.war'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PowerShell@2
    displayName: 'List Contents of Artifacts Directory'
    inputs:
      targetType: 'inline'
      script: |
        Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)" -Recurse

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'warfile'
      publishLocation: 'Container'

  - task: PowerShell@2
    displayName: 'Copy WAR file to Tomcat webapps directory'
    inputs:
      targetType: 'inline'
      script: |
        $warFiles = Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)\*.war"

        Write-Host "Listing WAR files in $(Build.ArtifactStagingDirectory):"
        foreach ($warFile in $warFiles) {
            Write-Host " - $($warFile.FullName)"
        }

        if ($warFiles.Count -eq 0) {
            Write-Host "No WAR files found in $(Build.ArtifactStagingDirectory)"
            exit 0  # Exit gracefully, as there might be scenarios where no WAR file is expected
        }

        $warFile = $warFiles[0]  # Assuming you have only one WAR file, adjust accordingly
        $tomcatWebappsDir = "C:\Program Files\Apache Software Foundation\Tomcat 10.1\webapps\ROOT"

        Write-Host "Copying $($warFile.FullName) to $tomcatWebappsDir"

        try {
            Copy-Item -Path $warFile.FullName -Destination $tomcatWebappsDir -ErrorAction Stop
            Write-Host "WAR file copied successfully!"
        } catch {
            Write-Host "Error copying WAR file: $_"
            exit 1  # Exit with an error code
        }
