trigger:
- master

pool:
  name: WindowVm

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy WAR'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21.0.2'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: CopyFiles@2
    inputs:
      Contents: '**/*.war'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'warfile'
      publishLocation: 'Container'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Tomcat service name (assuming it's installed as a service)
        $serviceName = 'Tomcat9'

        # Tomcat administrative credentials
        $adminUsername = 'admin'
        $adminPassword = 'admin'

        # Tomcat shutdown URL
        $shutdownUrl = "http://$adminUsername:$adminPassword@localhost:8080/manager/text/stop?path=/"

        # Check if the service exists
        if (Get-Service -Name $serviceName -ErrorAction SilentlyContinue) {
            try {
                # Stop Tomcat using the shutdown URL
                Invoke-WebRequest -Uri $shutdownUrl -Method POST -ErrorAction Stop

                # Wait for Tomcat to stop (adjust the sleep duration based on your Tomcat's shutdown time)
                Start-Sleep -Seconds 30

                # Start the Tomcat service
                Start-Service -Name $serviceName
            } catch {
                Write-Host "Failed to stop Tomcat: $_"
            }
        } else {
            Write-Host "Tomcat service '$serviceName' not found."
        }
