trigger:
- master

pool:
  name: WindowVm

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy WAR'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21.0.2'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: CopyFiles@2
    inputs:
      Contents: '**/*.war'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'warfile'
      publishLocation: 'Container'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Assuming Tomcat is running on the same Windows VM
        Copy-Item -Path '$(build.artifactstagingdirectory)\*.war' -Destination 'C:\path\to\tomcat\webapps'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Assuming Tomcat is running as a service, restart the service
        Restart-Service -Name 'TomcatServiceName'
