trigger:
  - master

pool:
  name: WindowVm

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21.0.2'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: CopyFiles@2
    inputs:
      Contents: '**/*.war'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'warfile'
      publishLocation: 'Container'

  - task: Docker@2
    inputs:
      containerRegistry: 'AzureDB2Acr'
      repository: 'abcdefgh'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: '2seviceconncn'
      appType: 'webApp'
      WebAppName: 'azureDb-web-app'
      deployToSlotOrASE: true
      ResourceGroupName: 'sandeepbiradar'
      SlotName: 'production'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
