trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '6e763d1d-34f0-4403-8eff-b3a54f6b743e'
  imageRepository: 'biradarsandeepsamplejavaapp'
  containerRegistry: 'azuredb2acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'windows-latest'  # Use a Windows-based image

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
