# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  name: WindowVm

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21.0.2'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: CopyFiles@2
    inputs:
      Contents: '**/*.war'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'warfile'
      publishLocation: 'Container'

  - task: PowerShell@2
    displayName: 'Copy WAR file to Tomcat webapps directory'
    inputs:
      targetType: 'inline'
      script: |
        $warFile = Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)\*.war"
        $tomcatWebappsDir = "C:\path\to\tomcat\webapps"  # Replace with the actual path to your Tomcat webapps directory
        Copy-Item -Path $warFile.FullName -Destination $tomcatWebappsDir

  - task: Docker@2
    inputs:
      containerRegistry: 'AzureDB2Acr'
      repository: 'abcdefgh'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
